### ISSUE TITLE
What is the structure of oasisMRI/A and oasisMRI/B directory 

### ISSUE THREAD

**Issue by alqurri77** [csbbbv/ColorMedGAN#1]
Hi;

Below code read from **colorization.py** class load images from **oasisMRI/A and oasisMRI/B** directory , what is the structure of this directory. Is there a script to generate images to populate these dirs:

```
train_loader_src = utils.data_load(os.path.join('/media/user/8f28289d-aa45-46ab-b9e4-a7d4d9f08b7e/shaobo/colorization_tmp_oasis/data/', args.src_data), 'train', transform, args.batch_size, shuffle=True, drop_last=True)
train_loader_tgt = utils.data_load(os.path.join('/media/user/8f28289d-aa45-46ab-b9e4-a7d4d9f08b7e/shaobo/colorization_tmp_oasis/data/', args.tgt_data), 'train', transform, args.batch_size, shuffle=True, drop_last=True)
test_loader_src = utils.data_load(os.path.join('/media/user/8f28289d-aa45-46ab-b9e4-a7d4d9f08b7e/shaobo/colorization_tmp_oasis/data/', args.src_data), 'test', transform, 1, shuffle=True, drop_last=True)
```

**Comment by TardisBlue2** [comment]
Hi,
oasisMRI/A is the folder of the source data, you can download it here : https://www.oasis-brains.org/#data,  oasisMRI/B is the folder of the source data, you can download it here:https://www.nlm.nih.gov/research/visible/getting_data.html.

We didn't generate folders with scripts, we manually put images into these folders. You can try to download them first and put the images directly into this folder. hope my answer can help you
