### ISSUE TITLE
oasisMRI/B and mask

### ISSUE THREAD

**Issue by alqurri77** [csbbbv/ColorMedGAN#4]
Hi;

I downloaded  the  the Visible Human Project data from https://data.lhncbc.nlm.nih.gov/public/Visible-Human/Female-Images/PNG_format/head/index.html. However, I'm abit confused if mask is required, because I only found the image. See below snapshot:

![image](https://user-images.githubusercontent.com/75499343/226211976-e87769c4-58d7-4bcf-86ae-1aa922b61821.png)

**Comment by TardisBlue2** [comment]
This does not require a mask label
